# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LIF-DAT.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog
import sr245
import dg535
import incDelay


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 455)
        MainWindow.setWindowIcon(QtGui.QIcon('laser_logo.jpg'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.saveGraphBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveGraphBtn.setGeometry(QtCore.QRect(90, 370, 62, 19))
        self.saveGraphBtn.setObjectName("saveGraphBtn")
        self.saveDataBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveDataBtn.setGeometry(QtCore.QRect(290, 370, 68, 19))
        self.saveDataBtn.setObjectName("saveDataBtn")
        self.bdelay = QtWidgets.QLineEdit(self.centralwidget)
        self.bdelay.setGeometry(QtCore.QRect(600, 140, 61, 16))
        self.bdelay.setObjectName("bdelay")
        self.comPortList = QtWidgets.QComboBox(self.centralwidget)
        self.comPortList.setGeometry(QtCore.QRect(600, 50, 61, 16))
        self.comPortList.setObjectName("comPortList")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.comPortList.addItem("")
        self.srPort = QtWidgets.QLabel(self.centralwidget)
        self.srPort.setGeometry(QtCore.QRect(530, 50, 61, 16))
        self.srPort.setWhatsThis("")
        self.srPort.setObjectName("srPort")
        self.GPIB_List = QtWidgets.QComboBox(self.centralwidget)
        self.GPIB_List.setGeometry(QtCore.QRect(600, 110, 61, 16))
        self.GPIB_List.setObjectName("GPIB_List")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.GPIB_List.addItem("")
        self.dgPort = QtWidgets.QLabel(self.centralwidget)
        self.dgPort.setGeometry(QtCore.QRect(530, 110, 61, 16))
        self.dgPort.setObjectName("dgPort")
        self.delInc = QtWidgets.QLineEdit(self.centralwidget)
        self.delInc.setGeometry(QtCore.QRect(600, 170, 61, 16))
        self.delInc.setObjectName("delInc")
        self.numPoints = QtWidgets.QLineEdit(self.centralwidget)
        self.numPoints.setGeometry(QtCore.QRect(600, 200, 61, 16))
        self.numPoints.setObjectName("numPoints")
        self.baseDelay = QtWidgets.QLabel(self.centralwidget)
        self.baseDelay.setGeometry(QtCore.QRect(530, 140, 61, 16))
        self.baseDelay.setObjectName("baseDelay")
        self.delayInc = QtWidgets.QLabel(self.centralwidget)
        self.delayInc.setGeometry(QtCore.QRect(530, 170, 61, 16))
        self.delayInc.setObjectName("delayInc")
        self.scanPoints = QtWidgets.QLabel(self.centralwidget)
        self.scanPoints.setGeometry(QtCore.QRect(530, 200, 61, 16))
        self.scanPoints.setObjectName("scanPoints")
        self.scanBtn = QtWidgets.QPushButton(self.centralwidget)
        self.scanBtn.setGeometry(QtCore.QRect(520, 370, 62, 19))
        self.scanBtn.setObjectName("scanBtn")
        self.abortBtn = QtWidgets.QPushButton(self.centralwidget)
        self.abortBtn.setGeometry(QtCore.QRect(620, 370, 62, 19))
        self.abortBtn.setObjectName("abortBtn")
        self.baseVal = QtWidgets.QLabel(self.centralwidget)
        self.baseVal.setGeometry(QtCore.QRect(610, 290, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baseVal.setFont(font)
        self.baseVal.setAutoFillBackground(True)
        self.baseVal.setText("")
        self.baseVal.setScaledContents(False)
        self.baseVal.setObjectName("baseVal")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 30, 461, 311))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(520, 30, 161, 231))
        self.groupBox.setObjectName("groupBox")
        self.submitSettings = QtWidgets.QPushButton(self.groupBox)
        self.submitSettings.setGeometry(QtCore.QRect(40, 200, 62, 19))
        self.submitSettings.setObjectName("submitSettings")
        self.gpibAddr = QtWidgets.QLabel(self.groupBox)
        self.gpibAddr.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.gpibAddr.setObjectName("gpibAddr")
        self.gpibAddrList = QtWidgets.QComboBox(self.groupBox)
        self.gpibAddrList.setGeometry(QtCore.QRect(80, 50, 61, 16))
        self.gpibAddrList.setObjectName("gpibAddrList")
        self.gpibAddrList.addItem("")
        self.gpibAddrList.addItem("")
        self.gpibAddrList.addItem("")
        self.gpibAddrList.addItem("")
        self.gpibAddrList.addItem("")
        self.gpibAddrList.addItem("")
        self.gpibAddrList.addItem("")
        self.gpibAddrList.addItem("")
        self.gpibAddrList.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 270, 161, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.baseLineBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.baseLineBtn.setGeometry(QtCore.QRect(10, 20, 62, 19))
        self.baseLineBtn.setObjectName("baseLineBtn")
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.saveGraphBtn.raise_()
        self.saveDataBtn.raise_()
        self.bdelay.raise_()
        self.comPortList.raise_()
        self.srPort.raise_()
        self.GPIB_List.raise_()
        self.dgPort.raise_()
        self.delInc.raise_()
        self.numPoints.raise_()
        self.baseDelay.raise_()
        self.delayInc.raise_()
        self.scanPoints.raise_()
        self.scanBtn.raise_()
        self.abortBtn.raise_()
        self.baseVal.raise_()
        self.graphicsView.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionThere_is_no_help_this_was_a_one_man_job = QtWidgets.QAction(MainWindow)
        self.actionThere_is_no_help_this_was_a_one_man_job.setObjectName("actionThere_is_no_help_this_was_a_one_man_job")
        self.actionGoogle_your_problems = QtWidgets.QAction(MainWindow)
        self.actionGoogle_your_problems.setObjectName("actionGoogle_your_problems")
        self.menuHelp.addAction(self.actionThere_is_no_help_this_was_a_one_man_job)
        self.menuHelp.addAction(self.actionGoogle_your_problems)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.baseLineBtn.clicked.connect(self.get_baseline)
        self.submitSettings.clicked.connect(self.submit_settings)
        self.saveGraphBtn.clicked.connect(self.save_graph)
        self.abortBtn.clicked.connect(self.abort)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LIF-DAT: Laser-Induced Fluorescence Data Acquisition Tool"))
        self.saveGraphBtn.setStatusTip(_translate("MainWindow", "Save the graph to a file"))
        self.saveGraphBtn.setText(_translate("MainWindow", "Save Graph"))
        self.saveGraphBtn.adjustSize()
        self.saveDataBtn.setStatusTip(_translate("MainWindow", "Save all raw data information to file"))
        self.saveDataBtn.setText(_translate("MainWindow", "Save Raw Data"))
        self.saveDataBtn.adjustSize()
        self.comPortList.setItemText(0, _translate("MainWindow", "COM1"))
        self.comPortList.setItemText(1, _translate("MainWindow", "COM2"))
        self.comPortList.setItemText(2, _translate("MainWindow", "COM3"))
        self.comPortList.setItemText(3, _translate("MainWindow", "COM4"))
        self.comPortList.setItemText(4, _translate("MainWindow", "COM5"))
        self.comPortList.setItemText(5, _translate("MainWindow", "COM6"))
        self.comPortList.setItemText(6, _translate("MainWindow", "COM7"))
        self.comPortList.setItemText(7, _translate("MainWindow", "COM8"))
        self.comPortList.setItemText(8, _translate("MainWindow", "COM9"))
        self.comPortList.setItemText(9, _translate("MainWindow", "COM10"))
        self.comPortList.setItemText(10, _translate("MainWindow", "COM11"))
        self.comPortList.setItemText(11, _translate("MainWindow", "COM12"))
        self.comPortList.setItemText(12, _translate("MainWindow", "COM13"))
        self.comPortList.setItemText(13, _translate("MainWindow", "COM14"))
        self.comPortList.setItemText(14, _translate("MainWindow", "COM15"))
        self.srPort.setText(_translate("MainWindow", "SR245 Port:"))
        self.GPIB_List.setItemText(0, _translate("MainWindow", "0"))
        self.GPIB_List.setItemText(1, _translate("MainWindow", "1"))
        self.GPIB_List.setItemText(2, _translate("MainWindow", "2"))
        self.GPIB_List.setItemText(3, _translate("MainWindow", "3"))
        self.GPIB_List.setItemText(4, _translate("MainWindow", "4"))
        self.GPIB_List.setItemText(5, _translate("MainWindow", "5"))
        self.GPIB_List.setItemText(6, _translate("MainWindow", "6"))
        self.GPIB_List.setItemText(7, _translate("MainWindow", "7"))
        self.GPIB_List.setItemText(8, _translate("MainWindow", "8"))
        self.GPIB_List.setItemText(9, _translate("MainWindow", "9"))
        self.GPIB_List.setItemText(10, _translate("MainWindow", "10"))
        self.GPIB_List.setItemText(11, _translate("MainWindow", "11"))
        self.GPIB_List.setItemText(12, _translate("MainWindow", "12"))
        self.GPIB_List.setItemText(13, _translate("MainWindow", "13"))
        self.GPIB_List.setItemText(14, _translate("MainWindow", "14"))
        self.GPIB_List.setItemText(15, _translate("MainWindow", "15"))
        self.GPIB_List.setItemText(16, _translate("MainWindow", "16"))
        self.dgPort.setText(_translate("MainWindow", "DG535 Port:"))
        self.baseDelay.setText(_translate("MainWindow", "Base Delay:"))
        self.delayInc.setText(_translate("MainWindow", "Delay Inc."))
        self.scanPoints.setText(_translate("MainWindow", "Scan Point #"))
        self.scanBtn.setStatusTip(_translate("MainWindow", "Conduct an auto-delay scan"))
        self.scanBtn.setText(_translate("MainWindow", "Scan"))
        self.abortBtn.setStatusTip(_translate("MainWindow", "Stop the current scan"))
        self.abortBtn.setText(_translate("MainWindow", "Abort"))
        self.groupBox.setTitle(_translate("MainWindow", "Settings"))
        self.submitSettings.setStatusTip(_translate("MainWindow", "Update system settings"))
        self.submitSettings.setText(_translate("MainWindow", "Set"))
        self.gpibAddr.setText(_translate("MainWindow", "DG535 Addr:"))
        self.gpibAddrList.setItemText(0, _translate("MainWindow", "GPIB0"))
        self.gpibAddrList.setItemText(1, _translate("MainWindow", "GPIB1"))
        self.gpibAddrList.setItemText(2, _translate("MainWindow", "GPIB2"))
        self.gpibAddrList.setItemText(3, _translate("MainWindow", "GPIB3"))
        self.gpibAddrList.setItemText(4, _translate("MainWindow", "GPIB4"))
        self.gpibAddrList.setItemText(5, _translate("MainWindow", "GPIB5"))
        self.gpibAddrList.setItemText(6, _translate("MainWindow", "GPIB6"))
        self.gpibAddrList.setItemText(7, _translate("MainWindow", "GPIB7"))
        self.gpibAddrList.setItemText(8, _translate("MainWindow", "GPIB9"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Baseline Signal"))
        self.baseLineBtn.setText(_translate("MainWindow", "Collect"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionThere_is_no_help_this_was_a_one_man_job.setText(_translate("MainWindow", "There is no help. This was a one-man job"))
        self.actionGoogle_your_problems.setText(_translate("MainWindow", "Google your problems"))

    def submit_settings(self):
        global comPort
        global gpibPort
        global baseDelay
        global delayInc
        global nPoints

        comPort = self.comPortList.currentText()
        gpibPort = self.gpibAddrList.currentText() + '::' + self.GPIB_List.currentText() + '::INSTR'
        baseDelay = self.bdelay.text()
        delayInc = self.delInc.text()
        nPoints = self.numPoints.text()
        print('Current values: \nCom Port: ', comPort, '\nGPIB Address: ', gpibPort, '\nBase Delay: ', baseDelay,
              '\nDelay Increment: ', delayInc, '\nNumber of Points per Scan: ', nPoints)

    def get_baseline(self):
        global boxcar
        global baseline

        try:
            boxcar = sr245.connect_boxcar(comPort)
            baseline = sr245.collect_baseline(boxcar, n=10)
            self.baseVal.setText(str(baseline))
        except Exception:
            self.error_popup(message="Boxcar failed to connect")

    def run_scan(self):
        global pulse_generator

        try:
            pulse_generator = dg535.connect_pulse_gen(gpibPort)
        except Exception:
            self.error_popup(message="Pulse Generator failed to connect")
            return None

        try:
            incDelay.run(boxcar, pulse_generator, baseDelay, delayInc, nPoints, baseline)
        except Exception:
            self.error_popup(message="LIF-DAT encountered an issue during the autoscan")

    def error_popup(self, message):
        msg = QMessageBox()
        msg.setWindowTitle("Error Warning")
        msg.setText(message)

        x = msg.exec_()

    def save_graph(self):
        filename = QFileDialog.getSaveFileName(None, "Save File")
        file = open(filename, 'w')
        testText = "TESTING"
        file.write(testText)
        file.close()
        #incDelay.save_figure(filename)

    def save_data(self):
        filename = QFileDialog.getSaveFileName(self, 'Save File')

    def abort(self):
        incDelay.abort_scan()


if __name__ == "__main__":
    os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    app = QtWidgets.QApplication(sys.argv)
    app.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app.setStyle('Windows')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
